// The client ID is read from .env, which is untracked, so it stays out of the repo.
// Copy .env.example to .env and paste the ID from https://developer.spotify.com/dashboard.
// Register this exact redirect URI in that app's settings.
export const SPOTIFY_CLIENT_ID = process.env.EXPO_PUBLIC_SPOTIFY_CLIENT_ID ?? '';
export const REDIRECT_URI = 'pureshuffle://callback';

// .env is read at bundle time, so a missing ID shows up as an empty string here
// rather than as a network error deep in the auth flow.
export function assertClientIdConfigured(): void {
  if (!SPOTIFY_CLIENT_ID) {
    throw new Error(
      'Missing EXPO_PUBLIC_SPOTIFY_CLIENT_ID. Copy .env.example to .env, add your Spotify client ID, then restart the dev server.'
    );
  }
}

export const SCOPES = [
  'user-library-read',
  'playlist-modify-public',
  'playlist-modify-private',
  'playlist-read-private',
];

export const PLAYLIST_NAME = 'Pure Shuffle';
export const PLAYLIST_DESCRIPTION =
  'Truly randomly shuffled Liked Songs, regenerated by Pure Shuffle. Play with Spotify shuffle OFF.';
